### ISSUE TITLE
Implementing watch service completely

### ISSUE THREAD

**Issue by Raman-79** [Raman-79/newtube#1]
Basic watch service implementation has been done, need to make the following fixes in the backend

- Integration between the backend and the frontend 
- Styling for the video grid 
- A watch player component to watch the video

**Comment by akkarn1689** [comment]
Hi @Raman-79 , I would like to work on this issue. Could you please assign it to me?

**Comment by Raman-79** [comment]
@akkarn1689 Yeah sure can you work on the frontend part as I'm working on the backend myself

**Comment by akkarn1689** [comment]
Sure, I’d be happy to take on the frontend.
Let me know any specifics...

**Comment by Raman-79** [comment]
@akkarn1689 Just a video grid for the home page and a video player with some basic features like

- Like 
- Play/Pause

**Comment by akkarn1689** [comment]
@Raman-79 Sure. Working on it.
